optimize: use raw udp conn to solve quic in quic problem
juicity/juicity pull request #103
Opened 2023-08-25 15:16 UTC by mzz2017

### Background

`Quic-in-quic` doesn't play well in the high loss network (loss rate greater than 15%).

This PR supports to utilize `Demultiplexing QUIC` to solve this problem. See <https://github.com/quic-go/quic-go/releases/tag/v0.38.0>. Specifically, when treating UDP traffic with a destination port of 443/8443/5201, use raw udp sockets (underlying transport) to send and receive packets.

### Checklist

- [ ] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/juicity/juicity

### Full Changelogs

- [Implement ...]

### Issue Reference

Closes #_[issue number]_

### Test Result

2023-08-26 02:44 UTC, yqlbu commented
I've tested it. Working like a charm.

2023-08-26 02:55 UTC, yqlbu requested changes

2023-08-26 02:55 UTC, yqlbu commented on server/server.go
> +			Msg("juicity received an [udp] request")
```suggestion
			Msg("juicity received a [udp] request")
```

Actually, we should stick to a instead of an because udp is pronounced as ju:dipi.

2023-08-26 09:47 UTC, mzz2017 commented on server/server.go
> +			Msg("juicity received an [udp] request")
Nice catch. Solved. Thanks!

2023-08-27 08:29 UTC, yqlbu approved these changes
Nice work! 素晴らしいね！

2023-08-27 10:37 UTC, merged