Add docker CI
juicity/juicity pull request #130
Opened 2023-10-21 10:20 UTC by EkkoG

### Background

Make deploy juicity server easier.

### Checklist

- [ ] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/juicity/juicity

### Full Changelogs

- Add docker CI

### Issue Reference

no

### Test Result

https://github.com/EkkoG/juicity/pkgs/container/juicity/139716504?tag=v0.3.1
https://github.com/EkkoG/juicity/pkgs/container/juicity/139709638?tag=main

2023-10-21 16:06 UTC, yqlbu requested changes
Could we please not pin the `sha` as a workflow reference?

We may pin `tag` as a reference instead.

E.g.

```yaml
# https://github.com/docker/metadata-action/tags
uses: docker/build-push-action@v5.0.0
```

2023-10-21 16:06 UTC, yqlbu commented on .github/workflows/docker-publish.yml
> +    tags: [ 'v*.*.*' ]
```suggestion
    tags: [ 'v*' ]
```

2023-10-22 00:59 UTC, EkkoG commented
All issue resolved.

New test result
https://github.com/EkkoG/juicity/actions/runs/6600686251
https://github.com/EkkoG/juicity/actions/runs/6600687992

2023-10-22 06:49 UTC, yqlbu approved these changes

2023-10-22 06:49 UTC, yqlbu commented
Thanks for your contribution!

2023-10-22 06:49 UTC, merged

2023-10-23 07:32 UTC, sjtuross commented
Great to have the official docker build. Please also add linux/arm64 arch.

2023-10-23 08:34 UTC, EkkoG commented
> Great to have the official docker build. Please also add linux/arm64 arch.

@sjtuross https://github.com/juicity/juicity/pull/133